general.import = [
    "~/.config/alacritty/font.toml",
    "~/.config/alacritty/key_bindings.toml",
    "~/.config/alacritty/env-dark.toml",
    #"~/.config/alacritty/themes/themes/gruvbox_dark.toml"
    ]

[window] 
opacity = 0.85
blur = true
option_as_alt = "Both"

[env]
TERM = "xterm-256color"
