" Bundles
    if has('vim_starting')
        set nocompatible               " Be iMproved
        set runtimepath+=~/.vim/bundle/neobundle.vim/
    endif
    call neobundle#begin(expand('~/.vim/bundle/'))
    NeoBundleFetch 'Shougo/neobundle.vim'

	" Leader Key
	let mapleader=","

    NeoBundle 'whyreal/wr_vim'
    NeoBundle 'garbas/vim-snipmate', {
    \   "depends": ['vim-scripts/vim-addon-mw-utils', 'tomtom/tlib_vim']
    \ }
    NeoBundle 'kannokanno/previm'
	let g:previm_open_cmd = 'open'
	"let g:previm_custom_css_path = '/Users/kanno/tmp/some.css'
    NeoBundle 'majutsushi/tagbar'
    NeoBundle 'vim-scripts/VOoM'
    "NeoBundle 'plasticboy/vim-markdown'
    "NeoBundle 'junegunn/vim-easy-align'
    call neobundle#end()
    filetype plugin indent on
    syntax on

" Edit
    set clipboard+=unnamed         " yank and paste with the system clipboard
    set autoread
    set fileencodings=utf-8,gbk,ucs-bom,cp936,gb18030,big5,euc-jp,euc-kr,latin1

    inoremap jj <Esc>
    vnoremap < <gv
    vnoremap > >gv
    nnoremap q; q:
    nnoremap <Leader>w :w<cr>
    nnoremap <Leader>q :q<cr>

    " ModeLine
    set modeline

    " Auto change input method (gui only)
    if has('gui_running')
        set noimdisable
        set iminsert=0
        set imsearch=0
    endif

" Ui
    set t_Co=256
	colorscheme desert_mod
    set guifont=menlo:h14
	set directory=/tmp
    set laststatus=2
    set hidden

    set mouse=a
    nnoremap <Leader>n :Explore<cr>
    nnoremap <2-LeftMouse> za

" Search
    set regexpengine=2
    set smartcase
    set ignorecase
    set hlsearch
    set incsearch
    "set tags=tags;/
    set wildmenu
    set wildmode=full
	set iskeyword=@,48-57,_,192-255,-,#,^.
    set path+=**

" Command mode
    cnoremap <C-F> <Right>
    cnoremap <C-B> <Left>
    cnoremap <M-F> <C-Right>
    cnoremap <M-B> <C-Left>
    cnoremap <C-A> <Home>
    cnoremap <C-E> <End>

" Insert Mode motion
    imap <M-j> <DOWN>
    imap <M-k> <UP>
    imap <M-h> <LEFT>
    imap <M-l> <RIGHT>
    imap <C-a> <HOME>
    imap <C-e> <END>

" vim: fdm=indent ts=4 sw=4
