" 修改 macvim shell, 解决无法加载 shell 环境变量的问题
"defaults write org.vim.MacVim MMLoginShellCommand /bin/zsh

" Package Manager {{{1
call plug#begin('~/.vim/plugged')

let mapleader=","
" basic plugins{{{2
Plug 'tpope/vim-sensible'
Plug 'rlue/vim-barbaric'
"Plug 'CodeFalling/fcitx-vim-osx'
"}}}
" COC{{{2
Plug 'neoclide/coc.nvim' , {'branch': 'release'}
    " if hidden is not set, TextEdit might fail.
    set hidden

    " Better display for messages
    "set cmdheight=2

    " Smaller updatetime for CursorHold & CursorHoldI
    set updatetime=300

    " don't give |ins-completion-menu| messages.
    set shortmess+=c

    " always show signcolumns
    "set signcolumn=yes

    " Use tab for trigger completion with characters ahead and navigate.
    " Use command ':verbose imap <tab>' to make sure tab is not mapped by other plugin.
    inoremap <silent><expr> <TAB>
          \ pumvisible() ? "\<C-n>" :
          \ <SID>check_back_space() ? "\<TAB>" :
          \ coc#refresh()
    inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

    function! s:check_back_space() abort
      let col = col('.') - 1
      return !col || getline('.')[col - 1]  =~# '\s'
    endfunction

    " Use <c-space> for trigger completion.
    inoremap <silent><expr> <c-space> coc#refresh()

    " Use <cr> for confirm completion, `<C-g>u` means break undo chain at current position.
    " Coc only does snippet and additional edit on confirm.
    inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

    " Use `[c` and `]c` for navigate diagnostics
    nmap <silent> [c <Plug>(coc-diagnostic-prev)
    nmap <silent> ]c <Plug>(coc-diagnostic-next)

    " Remap keys for gotos
    nmap <silent> gd <Plug>(coc-definition)
    nmap <silent> gy <Plug>(coc-type-definition)
    nmap <silent> gi <Plug>(coc-implementation)
    nmap <silent> gr <Plug>(coc-references)

    " Use K for show documentation in preview window
    nnoremap <silent> K :call <SID>show_documentation()<CR>

    function! s:show_documentation()
      if &filetype == 'vim'
        execute 'h '.expand('<cword>')
      else
        call CocAction('doHover')
      endif
    endfunction

    " Highlight symbol under cursor on CursorHold
    autocmd CursorHold * silent call CocActionAsync('highlight')

    " Remap for rename current word
    nmap <leader>rn <Plug>(coc-rename)

    " Remap for format selected region
    vmap <leader>f  <Plug>(coc-format-selected)
    nmap <leader>f  <Plug>(coc-format-selected)

    augroup mygroup
      autocmd!
      " Setup formatexpr specified filetype(s).
      autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
      " Update signature help on jump placeholder
      autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
    augroup end

    " Remap for do codeAction of selected region, ex: `<leader>aap` for current paragraph
    vmap <leader>a  <Plug>(coc-codeaction-selected)
    nmap <leader>a  <Plug>(coc-codeaction-selected)

    " Remap for do codeAction of current line
    nmap <leader>ac  <Plug>(coc-codeaction)
    " Fix autofix problem of current line
    nmap <leader>qf  <Plug>(coc-fix-current)

    " Use `:Format` for format current buffer
    command! -nargs=0 Format :call CocAction('format')

    " Use `:Fold` for fold current buffer
    command! -nargs=? Fold :call     CocAction('fold', <f-args>)

    " Using CocList
    " Show all diagnostics
    nnoremap <silent> <leader>la  :<C-u>CocList diagnostics<cr>
    " Manage extensions
    nnoremap <silent> <leader>le  :<C-u>CocList extensions<cr>
    " Show commands
    nnoremap <silent> <leader>lc  :<C-u>CocList commands<cr>
    " Find symbol of current document
    nnoremap <silent> <leader>lo  :<C-u>CocList outline<cr>
    " Search workspace symbols
    nnoremap <silent> <leader>ls  :<C-u>CocList --ignore-case -N -I symbols<cr>
    nnoremap <silent> <leader>lb  :<C-u>CocList --ignore-case -N buffers<cr>
    nnoremap <silent> <leader>b  :<C-u>CocList --ignore-case -N buffers<cr>
    nnoremap <silent> <leader>lf  :<C-u>CocList --ignore-case files<cr>
    nnoremap <silent> <leader>f  :<C-u>CocList --ignore-case files<cr>
    nnoremap <silent> <leader>lr  :<C-u>CocList --ignore-case -N mru<cr>
    nnoremap <silent> <leader>lm  :<C-u>CocList --ignore-case -N marks<cr>
    " Search
    nnoremap <leader>s  <Plug>(coc-workspaceSymbols)
    " Do default action for next item.
    nnoremap <silent> <leader>j  :<C-u>CocNext<CR>
    " Do default action for previous item.
    nnoremap <silent> <leader>k  :<C-u>CocPrev<CR>
    " Resume latest coc list
    nnoremap <silent> <leader>p  :<C-u>CocListResume<CR>

    function! StatusDiagnostic() abort
      let info = get(b:, 'coc_diagnostic_info', {})
      if empty(info) | return '' | endif
      let msgs = []
      if get(info, 'error', 0)
        call add(msgs, 'E' . info['error'])
      endif
      if get(info, 'warning', 0)
        call add(msgs, 'W' . info['warning'])
      endif
      return join(msgs, ' '). ' ' . get(g:, 'coc_status', '')
    endfunction

    set statusline=\ %t%m%r%h%w%{StatusDiagnostic()}\ %=%(%{&ff}\|%{(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\",B\":\"\")}%k\|%Y%)
    " coc-git
    set statusline^=%{get(g:,'coc_git_status','')}%{get(b:,'coc_git_status','')}%{get(b:,'coc_git_blame','')}
    "set statusline=\ %t%m%r%h%w%{StatusDiagnostic()}\ %=%(%{&ff}\|%{(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\",B\":\"\")}%k\|%Y%)\ %([%l,%v][%p%%]\ %)

    hi default CocHighlightText  guibg=darkyellow guifg=red ctermbg=223 ctermfg=red

    " Create markmap from the whole file
    nmap <Leader>vm <Plug>(coc-markmap-create)
    " Create markmap from the selected lines
    vmap <Leader>vm <Plug>(coc-markmap-create-v)

" coc-snippet {{{3
" Use <C-l> for trigger snippet expand.
imap <C-l> <Plug>(coc-snippets-expand)

" Use <C-j> for select text for visual placeholder of snippet.
vmap <C-j> <Plug>(coc-snippets-select)

" Use <C-j> for jump to next placeholder, it's default of coc.nvim
let g:coc_snippet_next = '<c-j>'

" Use <C-k> for jump to previous placeholder, it's default of coc.nvim
let g:coc_snippet_prev = '<c-k>'

" Use <C-j> for both expand and jump (make expand higher priority.)
imap <C-j> <Plug>(coc-snippets-expand-jump)
"}}}
"}}}
" 导航{{{2
let g:netrw_list_hide='\(^\|\s\s\)\zs\.\S\+'
let g:netrw_winsize=30
"let g:netrw_liststyle=3 "tree

Plug 'christoomey/vim-tmux-navigator'
Plug 'vim-voom/VOoM'
    let g:voom_tree_placement = 'right'
    let g:voom_ft_modes = {'markdown': 'pandoc'}
    let g:voom_always_allow_move_left = 1
    nnoremap <silent> <leader>vv :VoomToggle<CR>
Plug 'majutsushi/tagbar'
    nnoremap <leader>vt :TagbarToggle<cr>
    nnoremap <leader>t :TagbarToggle<cr>

"}}}
" 补全{{{2
Plug 'wellle/tmux-complete.vim'
    let g:tmuxcomplete#trigger = 'omnifunc'
Plug 'honza/vim-snippets'
Plug 'tpope/vim-surround'
"}}}
" 注释{{{2
Plug 'scrooloose/nerdcommenter'
"}}}
" 对齐{{{2
Plug 'junegunn/vim-easy-align'
    " Start interactive EasyAlign in visual mode (e.g. vipga)
    xmap ga <Plug>(EasyAlign)
    " Start interactive EasyAlign for a motion/text object (e.g. gaip)
    nmap ga <Plug>(EasyAlign)
"}}}
" Markdown{{{2
Plug 'lvht/tagbar-markdown'
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
    let g:vim_markdown_toc_autofit = 1
    "let g:vim_markdown_folding_style_pythonic = 1
    "let g:vim_markdown_override_foldtext = 0
    let g:html_wrong_comments=1
    "let g:vim_markdown_new_list_item_indent = 0
	" Highlight YAML front matter as used by Jekyll or Hugo.
	let g:vim_markdown_frontmatter = 1

"Plug 'previm/previm'
"    let g:previm_open_cmd="open"
"	let g:previm_show_header = 0

"}}}
" UML{{{2
"Plug 'scrooloose/vim-slumlord'
"Plug 'aklt/plantuml-syntax'
"    let g:plantuml_executable_script='~/.vim/plantuml/plantuml.sh'
"}}}
" Misc {{{2
Plug 'ekalinin/Dockerfile.vim'
Plug 'chr4/nginx.vim'

"Plug 'easymotion/vim-easymotion'
    "let g:EasyMotion_keys = 'ertyuidfghjkcvbnm,'
    "let g:EasyMotion_smartcase = 1
    "map f <Plug>(easymotion-prefix)

Plug 'jpalardy/vim-slime'
    let g:slime_target = "tmux"
    let g:slime_paste_file = "$HOME/.slime_paste"
    let g:slime_default_config = {"socket_name": "default", "target_pane": "{right-of}"}
" }}}
" Color Theme{{{2
Plug 'NLKNguyen/papercolor-theme'
"}}}

call plug#end()

filetype plugin indent on
syntax enable
" }}}
" Command {{{1
command! Dos2unix e ++ff=unix | %s/\r//g
"command! Md2doc !md2doc %
"command! Md2pdf !md2pdf %
command! Ssconfig tabe ~/.ShadowsocksX/user-rule.txt
command! Sshconfig tabe ~/Documents/Note/scripts/ssh.config.json
command! VimrcEdit tabe ~/.vim/vimrc
command! VimrcReload so ~/.vim/vimrc
"command! Worklog tabedit ~/Documents/Note/work.shortcut.md
" }}}
" Autocmd {{{1
"autocmd FileType c,cpp setlocal ai ts=4 sw=4 fdm=syntax
autocmd FileType go setlocal ai ts=4 sw=4 fdm=indent
autocmd FileType java,groovy setlocal ai ts=4 sw=4 tw=120 fdm=indent
autocmd FileType python,yaml,lua,sh,vim setlocal fdm=indent ai ts=4 sw=4
autocmd FileType markdown setlocal et ts=4 sw=4
" fix list 中 ”<" 高亮错误
autocmd FileType markdown syn cluster htmlTop contains=@Spell,htmlEndTag,htmlSpecialChar,htmlPreProc,htmlComment,htmlLink,javaScript,@htmlPreproc
autocmd FileType nginx setlocal ai ts=4 sw=4
autocmd FileType snippets setlocal ts=4 sw=4
autocmd FileType jsp,xml,html,css setlocal fdm=indent ai ts=2 sw=2
autocmd FileType javascript,typescript.tsx,json setlocal ai ts=2 sw=2 fdm=indent
autocmd BufNewFile,BufRead *.tsx set filetype=typescript.tsx
autocmd BufNewFile,BufRead *.jsx set filetype=javascript.jsx
autocmd BufNewFile,BufRead *.docker set filetype=Dockerfile
" default filetype
autocmd BufEnter * if &filetype == "" | setlocal ft=text | endif

au BufWritePost ~/.ShadowsocksX/user-rule.txt
            \ !genpac --format=pac
            \ --pac-proxy="SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080; DIRECT;"
            \ --user-rule-from=~/.ShadowsocksX/user-rule.txt
            \ --gfwlist-proxy="SOCKS5 127.0.0.1:1080;"
            \ > ~/.ShadowsocksX/gfwlist.js
au BufWritePost ~/Documents/Note/scripts/ssh.config.json
            \ !cd ~/Documents/Note/scripts/
            \ && ./template.rander.lua ssh.config.lrt ssh.config.json
            \ > ~/.ssh/config
            \ && ./template.rander.lua ssh.config.hosts.lrt ssh.config.json
            \ > ~/.ssh/config_hosts

" }}}
" Map {{{1
nnoremap q; q:
inoremap jj <ESC>
noremap! <c-a> <Home>
noremap! <c-e> <End>
noremap! <c-f> <Right>
noremap! <c-b> <Left>
noremap! <c-n> <Down>
noremap! <c-p> <Up>
inoremap <c-k> <c-o>D

nnoremap j gj
nnoremap k gk

" previous buffer
nnoremap gp :bp<cr>
" next buffer
nnoremap gn :bn<cr>
" last buffer
nnoremap go <c-^>
" previous tab, the key of next tab is default: gt
nnoremap gb gT

" change to current directory
nnoremap <leader>cd :lcd %:h<CR>

" terminal 
tnoremap <esc> <c-w>N

" save
nnoremap <leader>w :w<cr>

nnoremap <silent> <leader>vs :terminal<CR>
nnoremap <leader>ve :Explore<CR>

" }}}
" Options && Variables {{{1
"set number relativenumber
set noro
set foldlevel=99
set clipboard+=unnamed
set fileencodings=utf-8,gbk,ucs-bom,cp936,gb18030,big5,latin1
set modeline modelines=3
set smartcase ignorecase
set hlsearch
set mouse+=a
set ttymouse=xterm2
"set macmeta
" make 前自动保存
set autowrite

" 命令窗口
set cmdwinheight=20

"set synmaxcol=200
let loaded_matchparen = 1
set belloff=all

set directory=/tmp
set hidden

set splitbelow
set previewheight=8
set colorcolumn=+1
set bg=dark
"set tgc

if has('gui_running')
	set bg=light
    " 透明
    "set transparency=30
    " 模糊
    "set blurradius=20
    "set linespace=1
    set cursorline
    set guifont=Menlo-Bold:h12
	"set guifontwide=MicrosoftYaHei-Bold
	set guioptions=egtk
endif

colorscheme PaperColor
"}}}
" Cabbreviate {{{1
cabbrev h tab h
"}}}
" LUA {{{1
if has('lua')
    lua package.path = package.path .. ";" .. os.getenv("HOME") .. "/.vim/lua/?.lua"
    lua require("utils")
    function OpenWithSystemApp(coc_list_context)
        lua coc_list_open_file_with(vim.eval("a:coc_list_context"), "open")
    endfunction

    function OpenWithFinder(coc_list_context)
        lua coc_list_open_file_with(vim.eval("a:coc_list_context"), "open -R")
    endfunction
    "au FileType * lua detect_voom_type()
    command! -nargs=1 Edit lua edit_remote_file(<f-args>)
    command! -range TemplateRender <line1>,<line2>lua template_render()
    command! -range TemplateSet <line1>,<line2>lua template_set()
    command! ExcuteUnnamedRegister lua vim.command(vim.eval("@\""))
    command! ServerUpdateInfo lua update_server_info()
    nnoremap 0 :lua toggle_home_zero()<CR>
    command! Docs lua cd_workspace("~/Documents/vim-workspace/docs")
    command! DotFiles lua cd_workspace("~/code/whyreal/dotfiles/")
    command! -nargs=1 -complete=file Favorite lua docs_add_favorite(<f-args>)
endif

"}}}

" vim: fdm=marker
