" Bundles
    if has('vim_starting')
        set nocompatible               " Be iMproved
        set runtimepath+=~/.vim/bundle/neobundle.vim/
    endif
    call neobundle#begin(expand('~/.vim/bundle/'))
    NeoBundleFetch 'Shougo/neobundle.vim'

	" Leader Key
	let mapleader=","

    NeoBundle 'whyreal/wr_vim'
    NeoBundle 'garbas/vim-snipmate', {
    \   "depends": ['vim-scripts/vim-addon-mw-utils', 'tomtom/tlib_vim']
    \ }

    call neobundle#end()

    filetype plugin indent on
    syntax on

" Edit
    set pastetoggle=<leader>p
    set clipboard+=unnamed         " yank and paste with the system clipboard
    set autoread
    set fileencodings=utf-8,gbk,ucs-bom,cp936,gb18030,big5,euc-jp,euc-kr,latin1

    inoremap jj <Esc>
    vnoremap < <gv
    vnoremap > >gv

    " ModeLine
    set modeline

" Ui
    set hidden
    set mouse=a
    set t_Co=256
    colorscheme desert

    " Status line
    set laststatus=2

	set directory=/tmp

" Search
    set smartcase
    set ignorecase
    set hlsearch
    set incsearch
    "set tags=tags;/
    set wildmenu
    set wildmode=full
	set iskeyword=@,48-57,_,192-255,-,#,^.
    noremap n nzz
    noremap N Nzz
    set path+=**

" Command mode
    cnoremap <C-F> <Right>
    cnoremap <C-B> <Left>
    cnoremap <M-F> <C-Right>
    cnoremap <M-B> <C-Left>
    cnoremap <C-A> <Home>
    cnoremap <C-E> <End>

" Misc

    nnoremap <silent> ? :!open dict://<cword><CR><CR>

    " unfold/fold with mouse
    nnoremap <2-LeftMouse> za

    " generate tags file
    command! MakeTags !ctags -R .

    command! Dos2unix %s///g
