# doc: https://github.com/kamiyaa/joshuto/blob/main/docs/configuration/keymap.toml.md

[default_view]

keymap = [
  # bookmarks
  # ---------------
  { keys = ["c", "d", "h"], command = "cd ~/" },
  { keys = ["c", "d", "n"], command = "cd ~/Documents/DocBase/" },
  { keys = ["c", "d", "d"], command = "cd ~/Downloads" },

  { keys = ["c", "d", "0"], command = "cd ~/Documents/DocBase/0.未归档" },
  { keys = ["c", "d", "1"], command = "cd ~/code/whyreal/dotfiles/" },
  { keys = ["c", "d", "2"], command = "cd ~/.config/joshuto" },
  { keys = ["c", "d", "3"], command = "cd ~/.config/" },
  { keys = ["c", "d", " "], command = ":cd " },

  # cursor
  # -------------
  { keys = ["j"], command = "cursor_move_down" },
  { keys = ["k"], command = "cursor_move_up" },
  { keys = ["h"], command = "cd .." },
  { keys = ["l"], command = "open" },

  { keys = ["g", "g"], command = "cursor_move_home" },
  { keys = ["g", "h"], command = "cursor_move_page_home" },
  { keys = ["g", "m"], command = "cursor_move_page_middle" },
  { keys = ["g", "l"], command = "cursor_move_page_end" },
  { keys = ["G"], command = "cursor_move_end" },

  { keys = ["["], command = "parent_cursor_move_up" },
  { keys = ["]"], command = "parent_cursor_move_down" },

  # tab
  # ---------------
  { keys = [",", "t", "c"], command = "new_tab" },
  { keys = [",", "t", "m"], command = "new_tab --cursor" },
  { keys = [",", "t", "s"], command = "new_tab --current" },
  { keys = [",", "t", "q"], command = "close_tab" },
  { keys = ["q"], command = "close_tab" },
  { keys = ["\t"], command = "tab_switch 1" },
  { keys = ["backtab"], command = "tab_switch -1" },

  { keys = ["alt+1"], command = "tab_switch_index 1" },
  { keys = ["alt+2"], command = "tab_switch_index 2" },
  { keys = ["alt+3"], command = "tab_switch_index 3" },
  { keys = ["alt+4"], command = "tab_switch_index 4" },
  { keys = ["alt+5"], command = "tab_switch_index 5" },

  # file
  #---------------
  { keys = ["a", "d"], command = ":mkdir " },
  { keys = ["a", "f"], command = ":shell touch " },
  { keys = ["d", "d"], command = "delete_files" },
  { keys = ["d", "x"], command = "cut_files" },
  { keys = ["r", "n"], command = ":rename " },
  { keys = ["r", "a"], command = "rename_append" },
  { keys = ["r", "A"], command = "rename_prepend" },
  { keys = ["r", "b"], command = "bulk_rename" },
  { keys = ["\n"], command = "open" },

  # copy
  { keys = ["y", "y"], command = "copy_files" },
  { keys = ["y", "n"], command = "copy_filename" },
  { keys = ["y", "."], command = "copy_filename_without_extension" },
  { keys = ["y", "p"], command = "copy_filepath" },
  { keys = ["y", "d"], command = "copy_dirpath" },

  # paste
  { keys = ["p", "p"], command = "paste_files" },
  { keys = ["p", "o"], command = "paste_files --overwrite=true" },

  # select
  { keys = [" "], command = "select --toggle=true" },
  { keys = ["t"], command = "select --all=true --toggle=true" },

  { keys = ["="], command = "set_mode" },

  # search
  #---------------
  { keys = ["/"], command = ":search " },
  { keys = ["|"], command = ":search_inc " },
  { keys = ["\\"], command = ":search_glob " },
  { keys = ["S"], command = "search_fzf" },
  { keys = ["C"], command = "subdir_fzf" },

  { keys = ["n"], command = "search_next" },
  { keys = ["N"], command = "search_prev" },

  # sort
  #---------------
  { keys = ["s", "r"], command = "sort reverse" },
  { keys = ["s", "l"], command = "sort lexical" },
  { keys = ["s", "m"], command = "sort mtime" },
  { keys = ["s", "n"], command = "sort natural" },
  { keys = ["s", "s"], command = "sort size" },
  { keys = ["s", "e"], command = "sort ext" },

  # misc
  #---------------
  { keys = ["?"], command = "help" },
  { keys = ["ctrl+c"], command = "quit" },
  { keys = ["Q"], command = "quit --output-current-directory" },
  { keys = ["R"], command = "reload_dirlist" },
  { keys = ["g", "."], command = "toggle_hidden" },
  # arrow keys
  { keys = ["ctrl+u"], command = "cursor_move_page_up 0.5" },
  { keys = ["ctrl+d"], command = "cursor_move_page_down 0.5" },

  { keys = [":"], command = ":" },
  { keys = [";"], command = ":" },

  { keys = ["!"], command = ":shell " },
  { keys = ["w"], command = "show_tasks --exit-key=w" },


]

[task_view]

keymap = [
  # arrow keys
  { keys = ["arrow_up"], command = "cursor_move_up" },
  { keys = ["arrow_down"], command = "cursor_move_down" },
  { keys = ["home"], command = "cursor_move_home" },
  { keys = ["end"], command = "cursor_move_end" },

  # vim-like keybindings
  { keys = ["j"], command = "cursor_move_down" },
  { keys = ["k"], command = "cursor_move_up" },
  { keys = ["g", "g"], command = "cursor_move_home" },
  { keys = ["G"], command = "cursor_move_end" },

  { keys = ["w"], command = "show_tasks" },
  { keys = ["escape"], command = "show_tasks" },
]

[help_view]

keymap = [
  # arrow keys
  { keys = ["arrow_up"], command = "cursor_move_up" },
  { keys = ["arrow_down"], command = "cursor_move_down" },
  { keys = ["home"], command = "cursor_move_home" },
  { keys = ["end"], command = "cursor_move_end" },

  # vim-like keybindings
  { keys = ["j"], command = "cursor_move_down" },
  { keys = ["k"], command = "cursor_move_up" },
  { keys = ["g", "g"], command = "cursor_move_home" },
  { keys = ["G"], command = "cursor_move_end" },

  { keys = ["w"], command = "show_tasks" },
  { keys = ["escape"], command = "show_tasks" },
]
