#!/bin/bash

function start_vim_server() {
    mvim --servername $servername
    sleep 1
}

servername="`vim --serverlist`"

if [[ $servername == "" ]]; then
    echo "Starting vim server ..."
    start_vim_server
else
    vim --servername $servername --remote-tab $*  # send file
fi
