#!/bin/bash
servername="VIMD"

function start_vim_server() {
    mvim --servername $servername
    sleep 1
}

if [[ `vim --serverlist` == "" ]]; then
    echo "Starting vim server ..."
    start_vim_server
fi

if [[ $# != 0 ]]; then
    vim --servername $servername --remote-tab $*  # send file
fi
