#!/bin/bash

servername="`vim --serverlist`"

if [[ $servername == "" ]]; then
    echo "Starting vim server VIM ..."
    servername="VIM"
    mvim --servername $servername
    sleep 1
fi

if [[ $# -eq 0 ]]; then
    mvim --servername $servername
else
    mvim --servername $servername --remote-tab $@  # send file
fi
