# update zsh_plugins.sh
#antibody bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.sh


export _ZL_CMD="j"
source ~/.zsh_plugins.sh

autoload -Uz compinit && compinit

# compdef vs='sshrc'
# compdef ssh.excute_local_script='sshrc'
# compdef _sshwr scp
# compdef _sshwr ssh
# compdef _sshwr sftp

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# vim: fdm=marker sw=4 ts=4 et ft=zsh

