set nocompatible
filetype off

" set default 'runtimepath' (without ~/.vim folders)
let &runtimepath = printf('%s/vimfiles,%s,%s/vimfiles/after', $VIM, $VIMRUNTIME, $VIM)
" what is the name of the directory containing this file?
let s:portable = expand('<sfile>:p:h')
" add the directory to 'runtimepath'
let &runtimepath = printf('%s,%s', &runtimepath, s:portable)
let &runtimepath = printf('%s, %s/nginx.vim/', &runtimepath, s:portable)
let &runtimepath = printf('%s, %s/vim-sensible/', &runtimepath, s:portable)

filetype plugin indent on
syntax enable

set cursorline
set foldlevel=99
set clipboard+=unnamed
set autoread
set fileencodings=utf-8,gbk,ucs-bom,cp936,gb18030,big5,euc-jp,euc-kr,latin1
set modeline
set modelines=3
set smartcase
set ignorecase
set hlsearch
set incsearch
set wildmode=full
set mouse=a

vnoremap < <gv
vnoremap > >gv
nnoremap q; q:
nnoremap ; :
nnoremap : ;
vnoremap ; :
vnoremap : ;
nnoremap n nzz
nnoremap N Nzz
nnoremap <expr> n  'Nn'[v:searchforward]
nnoremap <expr> N  'nN'[v:searchforward]
nnoremap <2-LeftMouse> za

" change to current directory
nnoremap <silent> <leader>cd :lcd %:h<CR>

" Ui{{{1
set statusline=\ %F%m%r%h%w\ %=%(%{&ff}\|%{(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\",B\":\"\")}%k\|%Y%)\ %([%l,%v][%p%%]\ %)
set laststatus=2
set synmaxcol=200
let loaded_matchparen = 1
set noerrorbells
set novisualbell
set t_vb=

set directory=/tmp
set hidden
set splitbelow
set previewheight=8

" not display ~ for blank line
highlight EndOfBuffer ctermfg=black guifg=bg
"}}}
" Command {{{1

" update pac file
command! Dos2unix e ++ff=unix | %s///g
command! FormatJSON %!python -m json.tool

nnoremap <silent> ? :!open dict://<cword><CR><CR>
"}}}
" Autocmd {{{1
"
autocmd FileType nginx setlocal fdm=indent ai ts=4 sw=4 tw=80
autocmd FileType json,yaml,xml,html,css setlocal fdm=indent ai ts=2 sw=2 tw=80

" }}}
